Webmap/Models/CLINIC.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLINIC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLINIC()
        {
            this.DOCTORS = new HashSet<DOCTOR>();
        }
    
        public int ClinicID { get; set; }
        public string CLINICGoogleUID { get; set; }
        public string ClinicName { get; set; }
        public string CLINICADDRESS { get; set; }
        public string ClinicEmail { get; set; }
        public string ClinicTelePhone { get; set; }
        public string CLINICWorkingHours { get; set; }
        public string ClinicWebsite { get; set; }
        public Nullable<int> USERID { get; set; }
        public string USERNAME { get; set; }
        public System.DateTime USERSearchDATETIME { get; set; }
        public string CLINICLOCATION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTOR> DOCTORS { get; set; }
    }
}

Webmap/Controllers/CLINICsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Webmap.Models;

namespace Webmap.Controllers
{
    public class CLINICsController : Controller
    {
        private DBPATIENTNOWAITDataEntities db = new DBPATIENTNOWAITDataEntities();

        // GET: CLINICs
        public ActionResult Index()
        {
            return View(db.CLINICS.ToList());
        }

        // GET: CLINICs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CLINIC cLINIC = db.CLINICS.Find(id);
            if (cLINIC == null)
            {
                return HttpNotFound();
            }
            return View(cLINIC);
        }

        // GET: CLINICs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CLINICs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClinicID,CLINICGoogleUID,ClinicName,CLINICADDRESS,ClinicEmail,ClinicTelePhone,CLINICWorkingHours,ClinicWebsite,USERID,USERNAME,USERSearchDATETIME")] CLINIC cLINIC)
        {
            if (ModelState.IsValid)
            {
                db.CLINICS.Add(cLINIC);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cLINIC);
        }

        // GET: CLINICs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CLINIC cLINIC = db.CLINICS.Find(id);
            if (cLINIC == null)
            {
                return HttpNotFound();
            }
            return View(cLINIC);
        }

        // POST: CLINICs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClinicID,CLINICGoogleUID,ClinicName,CLINICADDRESS,ClinicEmail,ClinicTelePhone,CLINICWorkingHours,ClinicWebsite,USERID,USERNAME,USERSearchDATETIME")] CLINIC cLINIC)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cLINIC).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cLINIC);
        }

        // GET: CLINICs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CLINIC cLINIC = db.CLINICS.Find(id);
            if (cLINIC == null)
            {
                return HttpNotFound();
            }
            return View(cLINIC);
        }

        // POST: CLINICs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CLINIC cLINIC = db.CLINICS.Find(id);
            db.CLINICS.Remove(cLINIC);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Webmap/Controllers/DOCTORsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Webmap.Models;

namespace Webmap.Controllers
{
    public class DOCTORsController : Controller
    {
        private DBPATIENTNOWAITDataEntities db = new DBPATIENTNOWAITDataEntities();

        // GET: DOCTORs
        public ActionResult Index()
        {
            var dOCTORS = db.DOCTORS.Include(d => d.CLINIC);
            return View(dOCTORS.ToList());
        }

        // GET: DOCTORs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DOCTOR dOCTOR = db.DOCTORS.Find(id);
            if (dOCTOR == null)
            {
                return HttpNotFound();
            }
            return View(dOCTOR);
        }

        // GET: DOCTORs/Create
        public ActionResult Create()
        {
            ViewBag.ClinicID = new SelectList(db.CLINICS, "ClinicID", "CLINICGoogleUID");
            return View();
        }

        // POST: DOCTORs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DOCTORID,DOCTORNAME,DOCTORADDRESS,DOCTOREmail,DOCTORTelePhone,DOCTORWorkingHours,ClinicID,CLINICGoogleUID,ClinicName,USERID,USERNAME,USERSearchDATETIME")] DOCTOR dOCTOR)
        {
            if (ModelState.IsValid)
            {
                db.DOCTORS.Add(dOCTOR);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClinicID = new SelectList(db.CLINICS, "ClinicID", "CLINICGoogleUID", dOCTOR.ClinicID);
            return View(dOCTOR);
        }

        // GET: DOCTORs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DOCTOR dOCTOR = db.DOCTORS.Find(id);
            if (dOCTOR == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClinicID = new SelectList(db.CLINICS, "ClinicID", "CLINICGoogleUID", dOCTOR.ClinicID);
            return View(dOCTOR);
        }

        // POST: DOCTORs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DOCTORID,DOCTORNAME,DOCTORADDRESS,DOCTOREmail,DOCTORTelePhone,DOCTORWorkingHours,ClinicID,CLINICGoogleUID,ClinicName,USERID,USERNAME,USERSearchDATETIME")] DOCTOR dOCTOR)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dOCTOR).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClinicID = new SelectList(db.CLINICS, "ClinicID", "CLINICGoogleUID", dOCTOR.ClinicID);
            return View(dOCTOR);
        }

        // GET: DOCTORs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DOCTOR dOCTOR = db.DOCTORS.Find(id);
            if (dOCTOR == null)
            {
                return HttpNotFound();
            }
            return View(dOCTOR);
        }

        // POST: DOCTORs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DOCTOR dOCTOR = db.DOCTORS.Find(id);
            db.DOCTORS.Remove(dOCTOR);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Webmap/Views/CLINICs/Create.cshtml
@model Webmap.Models.CLINIC

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CLINIC</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClinicID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CLINICGoogleUID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CLINICGoogleUID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CLINICGoogleUID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CLINICADDRESS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CLINICADDRESS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CLINICADDRESS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicTelePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicTelePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicTelePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CLINICWorkingHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CLINICWorkingHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CLINICWorkingHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicWebsite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicWebsite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicWebsite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.USERID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.USERID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.USERID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.USERNAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.USERNAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.USERNAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.USERSearchDATETIME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.USERSearchDATETIME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.USERSearchDATETIME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Webmap/Views/CLINICs/Delete.cshtml
@model Webmap.Models.CLINIC

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CLINIC</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CLINICGoogleUID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLINICGoogleUID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClinicName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClinicName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CLINICADDRESS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLINICADDRESS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClinicEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClinicEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClinicTelePhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClinicTelePhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CLINICWorkingHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLINICWorkingHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClinicWebsite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClinicWebsite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USERID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USERNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERNAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USERSearchDATETIME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERSearchDATETIME)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Webmap/Views/CLINICs/Details.cshtml
@model Webmap.Models.CLINIC

@{
    ViewBag.Title = "Details";
}

<h2>CLINIC Details</h2>

<div>
    @*<h4>CLINIC</h4>*@
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.CLINICGoogleUID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLINICGoogleUID)
        </dd>*@

        <dt>
            @*@Html.DisplayNameFor(model => model.ClinicName)*@
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClinicName)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.CLINICADDRESS)*@
            Address
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLINICADDRESS)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.ClinicEmail)*@
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClinicEmail)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.ClinicTelePhone)*@
            Telephone
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClinicTelePhone)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.CLINICWorkingHours)*@
            WorkingHours
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLINICWorkingHours)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.ClinicWebsite)*@
            Website
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClinicWebsite)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.USERID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USERNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERNAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USERSearchDATETIME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERSearchDATETIME)
        </dd>*@

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.ClinicID }) |*@
    @Html.ActionLink("Back to Clinic List", "Index")
</p>
<table class="table">
    <tr>
        <th>
            Doctor Name
        </th>
        <th>
            Telephone
        </th>
        <th>
            Working Hours
        </th>
        <th>
            Patient Comments
        </th>
    </tr>

    @foreach (var item in Model.DOCTORS)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DOCTORNAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOCTORTelePhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOCTORWorkingHours)
            </td>
            <td>
                @*@Html.ActionLink("List of Doctors", "Index", "DOCTORs")*@
                @Html.ActionLink("Doctors ReViews", "Details" + "/" + item.DOCTORID, "DOCTORs")                
            </td>
        </tr>
    }
</table>

Webmap/Views/CLINICs/Edit.cshtml
@model Webmap.Models.CLINIC

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CLINIC</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ClinicID)

        <div class="form-group">
            @Html.LabelFor(model => model.CLINICGoogleUID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CLINICGoogleUID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CLINICGoogleUID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CLINICADDRESS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CLINICADDRESS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CLINICADDRESS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicTelePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicTelePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicTelePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CLINICWorkingHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CLINICWorkingHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CLINICWorkingHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicWebsite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicWebsite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicWebsite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.USERID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.USERID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.USERID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.USERNAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.USERNAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.USERNAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.USERSearchDATETIME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.USERSearchDATETIME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.USERSearchDATETIME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Webmap/Views/CLINICs/Index.cshtml
@model IEnumerable<Webmap.Models.CLINIC>

@{
    ViewBag.Title = "Index";
}

<h2>CLINIC LIST</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        @*<th>

            @Html.DisplayNameFor(model => model.CLINICGoogleUID)
        </th>*@
        <th>
            @*@Html.DisplayNameFor(model => model.ClinicName)*@
            Name
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.CLINICADDRESS)*@
            Address
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.ClinicEmail)*@
            Email
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.ClinicTelePhone)*@
            Telephone
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.CLINICWorkingHours)*@
            WorkingHours
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.ClinicWebsite)*@
            WebSite
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.USERID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.USERNAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.USERSearchDATETIME)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @*<td>
            @Html.DisplayFor(modelItem => item.CLINICGoogleUID)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.ClinicName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CLINICADDRESS)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClinicEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClinicTelePhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CLINICWorkingHours)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClinicWebsite)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.USERID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.USERNAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.USERSearchDATETIME)
        </td>*@
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.ClinicID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ClinicID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ClinicID })*@
            @Html.ActionLink("Details", "Details", new { id = item.ClinicID })
        </td>
    </tr>
}

</table>