Webmap/Models/DOCTOR.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webmap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR()
        {
            this.DOCTORSUSERRATINGS = new HashSet<DOCTORSUSERRATING>();
        }
    
        public int DOCTORID { get; set; }
        public string DOCTORNAME { get; set; }
        public string DOCTORADDRESS { get; set; }
        public string DOCTOREmail { get; set; }
        public string DOCTORTelePhone { get; set; }
        public string DOCTORWorkingHours { get; set; }
        public Nullable<int> ClinicID { get; set; }
        public string CLINICGoogleUID { get; set; }
        public string ClinicName { get; set; }
        public Nullable<int> USERID { get; set; }
        public string USERNAME { get; set; }
        public System.DateTime USERSearchDATETIME { get; set; }
    
        public virtual CLINIC CLINIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTORSUSERRATING> DOCTORSUSERRATINGS { get; set; }
    }
}

Webmap/Controllers/CLINICsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Webmap.Models;

namespace Webmap.Controllers
{
    public class CLINICsController : Controller
    {
        private DBPATIENTNOWAITDataEntities db = new DBPATIENTNOWAITDataEntities();

        // GET: CLINICs
        public ActionResult Index()
        {
            return View(db.CLINICS.ToList());
        }

        // GET: CLINICs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CLINIC cLINIC = db.CLINICS.Find(id);
            if (cLINIC == null)
            {
                return HttpNotFound();
            }
            return View(cLINIC);
        }

        // GET: CLINICs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CLINICs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClinicID,CLINICGoogleUID,ClinicName,CLINICADDRESS,ClinicEmail,ClinicTelePhone,CLINICWorkingHours,ClinicWebsite,USERID,USERNAME,USERSearchDATETIME")] CLINIC cLINIC)
        {
            if (ModelState.IsValid)
            {
                db.CLINICS.Add(cLINIC);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cLINIC);
        }

        // GET: CLINICs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CLINIC cLINIC = db.CLINICS.Find(id);
            if (cLINIC == null)
            {
                return HttpNotFound();
            }
            return View(cLINIC);
        }

        // POST: CLINICs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClinicID,CLINICGoogleUID,ClinicName,CLINICADDRESS,ClinicEmail,ClinicTelePhone,CLINICWorkingHours,ClinicWebsite,USERID,USERNAME,USERSearchDATETIME")] CLINIC cLINIC)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cLINIC).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cLINIC);
        }

        // GET: CLINICs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CLINIC cLINIC = db.CLINICS.Find(id);
            if (cLINIC == null)
            {
                return HttpNotFound();
            }
            return View(cLINIC);
        }

        // POST: CLINICs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CLINIC cLINIC = db.CLINICS.Find(id);
            db.CLINICS.Remove(cLINIC);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Webmap/Controllers/DOCTORsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Webmap.Models;

namespace Webmap.Controllers
{
    public class DOCTORsController : Controller
    {
        private DBPATIENTNOWAITDataEntities db = new DBPATIENTNOWAITDataEntities();

        // GET: DOCTORs
        public ActionResult Index()
        {
            var dOCTORS = db.DOCTORS.Include(d => d.CLINIC);
            return View(dOCTORS.ToList());
        }

        // GET: DOCTORs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DOCTOR dOCTOR = db.DOCTORS.Find(id);
            if (dOCTOR == null)
            {
                return HttpNotFound();
            }
            return View(dOCTOR);
        }

        // GET: DOCTORs/Create
        public ActionResult Create()
        {
            ViewBag.ClinicID = new SelectList(db.CLINICS, "ClinicID", "CLINICGoogleUID");
            return View();
        }

        // POST: DOCTORs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DOCTORID,DOCTORNAME,DOCTORADDRESS,DOCTOREmail,DOCTORTelePhone,DOCTORWorkingHours,ClinicID,CLINICGoogleUID,ClinicName,USERID,USERNAME,USERSearchDATETIME")] DOCTOR dOCTOR)
        {
            if (ModelState.IsValid)
            {
                db.DOCTORS.Add(dOCTOR);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClinicID = new SelectList(db.CLINICS, "ClinicID", "CLINICGoogleUID", dOCTOR.ClinicID);
            return View(dOCTOR);
        }

        // GET: DOCTORs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DOCTOR dOCTOR = db.DOCTORS.Find(id);
            if (dOCTOR == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClinicID = new SelectList(db.CLINICS, "ClinicID", "CLINICGoogleUID", dOCTOR.ClinicID);
            return View(dOCTOR);
        }

        // POST: DOCTORs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DOCTORID,DOCTORNAME,DOCTORADDRESS,DOCTOREmail,DOCTORTelePhone,DOCTORWorkingHours,ClinicID,CLINICGoogleUID,ClinicName,USERID,USERNAME,USERSearchDATETIME")] DOCTOR dOCTOR)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dOCTOR).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClinicID = new SelectList(db.CLINICS, "ClinicID", "CLINICGoogleUID", dOCTOR.ClinicID);
            return View(dOCTOR);
        }

        // GET: DOCTORs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DOCTOR dOCTOR = db.DOCTORS.Find(id);
            if (dOCTOR == null)
            {
                return HttpNotFound();
            }
            return View(dOCTOR);
        }

        // POST: DOCTORs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DOCTOR dOCTOR = db.DOCTORS.Find(id);
            db.DOCTORS.Remove(dOCTOR);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Webmap/Views/DOCTORs/Create.cshtml
@model Webmap.Models.DOCTOR

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DOCTOR</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DOCTORID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOCTORID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOCTORID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOCTORNAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOCTORNAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOCTORNAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOCTORADDRESS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOCTORADDRESS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOCTORADDRESS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOCTOREmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOCTOREmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOCTOREmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOCTORTelePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOCTORTelePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOCTORTelePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOCTORWorkingHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOCTORWorkingHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOCTORWorkingHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicID, "ClinicID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClinicID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClinicID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CLINICGoogleUID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CLINICGoogleUID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CLINICGoogleUID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.USERID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.USERID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.USERID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.USERNAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.USERNAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.USERNAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.USERSearchDATETIME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.USERSearchDATETIME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.USERSearchDATETIME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Webmap/Views/DOCTORs/Delete.cshtml
@model Webmap.Models.DOCTOR

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DOCTOR</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DOCTORNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOCTORNAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOCTORADDRESS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOCTORADDRESS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOCTOREmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOCTOREmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOCTORTelePhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOCTORTelePhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOCTORWorkingHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOCTORWorkingHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CLINICGoogleUID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLINICGoogleUID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClinicName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClinicName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USERID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USERNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERNAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USERSearchDATETIME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERSearchDATETIME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CLINIC.CLINICGoogleUID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLINIC.CLINICGoogleUID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Webmap/Views/DOCTORs/Details.cshtml
@model Webmap.Models.DOCTOR

@{
    ViewBag.Title = "Details";
}

<h2>DOCTOR Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
           Doctor Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOCTORNAME)
        </dd>

        <dt>
            Address
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOCTORADDRESS)
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOCTOREmail)
        </dd>

        <dt>
            TelePhone
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOCTORTelePhone)
        </dd>

        <dt>
            WorkingHours
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOCTORWorkingHours)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.CLINICGoogleUID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLINICGoogleUID)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.ClinicName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClinicName)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.USERID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USERNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERNAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.USERSearchDATETIME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USERSearchDATETIME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CLINIC.CLINICGoogleUID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLINIC.CLINICGoogleUID)
        </dd>*@

    </dl>
</div>
@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DOCTORID }) |
    @Html.ActionLink("Back to List", "Index")  
</p>*@
<table class="table">
    <tr>
        <th>
            Patient Name
        </th>
        <th>
            Comments
        </th>
    </tr>

    @foreach (var item in Model.DOCTORSUSERRATINGS)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.USERNAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.USERCOMMENTS)
            </td>
        </tr>
    }
</table>
           
@Html.ActionLink("Back To Clinics Details", "Details" + "/" + Model.ClinicID, "CLINICs")            

<div>
    @*<table>
        <tr>
            <td width="100%">
                <button type="button" id="btnShowPopup" class="btn btn-primary" data-toggle="modal"
                        data-target="#exampleModal">
                    Launch Book Appointement
                </button>                
            </td>
        </tr>
    </table>*@
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Doctor Appointement Info</h4>
            </div>
            <div class="modal-body">
                <strong>
                    Dr Etedal Mohammad Hifzi Aamri
                    Toronto General Hospital
                </strong><br />
                200 Elizabeth St, Toronto, ON M5G 2C4<br />
                patientrelations@uhn.ca<br />
                +1-(416) 340-4800<br /><br />
                Open 24 hours
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Email</button>
                <button type="button" class="btn btn-primary">Send Mobile SMS</button>
            </div>
        </div>
    </div>
</div>

Webmap/Views/DOCTORs/Edit.cshtml
@model Webmap.Models.DOCTOR

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DOCTOR</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DOCTORID)

        <div class="form-group">
            @Html.LabelFor(model => model.DOCTORNAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOCTORNAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOCTORNAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOCTORADDRESS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOCTORADDRESS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOCTORADDRESS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOCTOREmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOCTOREmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOCTOREmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOCTORTelePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOCTORTelePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOCTORTelePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOCTORWorkingHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOCTORWorkingHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOCTORWorkingHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicID, "ClinicID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClinicID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClinicID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CLINICGoogleUID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CLINICGoogleUID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CLINICGoogleUID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClinicName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClinicName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClinicName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.USERID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.USERID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.USERID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.USERNAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.USERNAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.USERNAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.USERSearchDATETIME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.USERSearchDATETIME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.USERSearchDATETIME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}